import matplotlib.pyplot as plt
import pandas as pd
import json
# Load the JSON data into a Pandas DataFrame
file_path = "../../data/toxic/500toxic_scores.json"
with open(file_path, "r") as file:
    data = json.load(file)

df = pd.DataFrame(data)

# Generate scatter plots for each model's response toxicity
models = ["BLOOM", "Gemma", "LLaMA", "Mistral"]

for model in models:
    plt.figure()
    plt.scatter(df["toxicity"], df[model], alpha=0.7)
    plt.title(f"Toxicity of {model}")
    plt.xlabel("Prompt Toxicity")
    plt.ylabel(f"{model} Response Toxicity")
    #plt.xlim(0, 1)
    plt.ylim(0, 1)
    plt.grid(True)
    plt.savefig(f"../../figures/toxic/{model}.svg", format="svg", transparent=True)

plt.show()

# create scatter-plots using the data in "data/random/100random_scores.json", this file contains a "toxicity" column, which should be the x-axis for all plots, and four more columns "BLOOM", "Gemma", "LLaMA", and "Mistral" which should be on each of the for y-axes. The values in the "toxicity" column represents the toxicity of the prompt, while the other four collumns represent the toxicity of the response generated by each of these LLMs when given these responses